package org.firstinspires.ftc.teamcode.autonmous;

import com.acmerobotics.roadrunner.Action;
import com.acmerobotics.roadrunner.Pose2d;
import com.acmerobotics.roadrunner.Vector2d;
import com.acmerobotics.roadrunner.ftc.Actions;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;

import org.firstinspires.ftc.teamcode.OpModeGroups;
import org.firstinspires.ftc.teamcode.RR.MecanumDrive;
import org.firstinspires.ftc.teamcode.robot.Intake;

@Autonomous(name = "RRLocalize Check", group = OpModeGroups.TESTS)
public class RRTest extends LinearOpMode {
	MecanumDrive mecanumDrive;

	@Override
	public void runOpMode() throws InterruptedException {
		hardwareMap.getClass();
		Intake intake = new Intake(this);
		intake.init();
		intake.setSpeed(1);
		intake.loop();
		final Pose2d initalPose = new Pose2d(0, 0, Math.PI / 2);
		mecanumDrive = new MecanumDrive(hardwareMap, initalPose);
		Action firstMove = mecanumDrive.actionBuilder(initalPose)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 24))
				.waitSeconds(1)
				.strafeTo(new Vector2d(24, 0))
				.waitSeconds(1)
				.strafeTo(new Vector2d(0, 0))
				.waitSeconds(1)
				.build();

		waitForStart();

		Actions.runBlocking(firstMove);
	}
}
